name: Create a branch
on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'Branch Type'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - hotfix
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print the input values
        env:
          BRANCH_TYPE: ${{ inputs.branch_type }}
          VERSION: ${{ inputs.version }}
        shell: bash
        run: |
          echo "Branch Type: ${BRANCH_TYPE}, version: ${VERSION}"
          git fetch -a
          git branch -r | while read -r branch; do
            echo "Branch: ${branch}"
          done
          git switch -C $BRANCH_TYPE/$VERSION origin/main
          git push origin $BRANCH_TYPE/$VERSION

          git branch -r | while read -r branch; do
            echo "Branch: ${branch}"
          done
