name: Create a branch
on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'Branch Type'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - hotfix
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print the input values
        env:
          BRANCH_TYPE: ${{ inputs.branch_type }}
          VERSION: ${{ inputs.version }}
        shell: bash
        run: |
          echo "Branch Type: ${BRANCH_TYPE}, version: ${VERSION}"
          NEW_BRANCH="${BRANCH_TYPE}/${VERSION}"
          echo "New Branch: ${NEW_BRANCH}"
          git fetch -a
          EXIST_BRANCH=$(git branch -r)
          echo "EXIST_BRANCH1: ${EXIST_BRANCH}"
          EXIST_BRANCH=$(git branch -r | grep "origin/${NEW_BRANCH}")
          echo "EXIST_BRANCH: ${EXIST_BRANCH}"
          if [ -n "$EXIST_BRANCH" ]; then
            echo "$NEW_BRANCH branch already exists"
            exit 0
          fi
          git switch -C $NEW_BRANCH origin/main
          git push origin $NEW_BRANCH

          git branch -r | while read -r branch; do
            echo "Branch: ${branch}"
          done
